name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/backend.yml
      - 'backend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: joanne-blog

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        if: success() # Only run if the build and push succeeded
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}