name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy.yml'

# Add permissions for the job
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          # Use the root package-lock.json for caching
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        # Run npm install from the root directory
        run: npm install

      - name: Build project
        # Run the build script for the frontend workspace from the root
        run: npm run build --workspace=frontend

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: frontend/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          # Download to a dist folder in the root
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Publish from the root dist folder
          publish_dir: ./dist