name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'frontend/**' # 🎯 Only run this workflow for changes in the frontend folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write      # Give permission to deploy to GitHub Pages
      id-token: write   # Give permission for OIDC token
    
    defaults:
      run:
        working-directory: ./frontend # Run all commands inside the frontend folder

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci # 'ci' is faster and safer for CI environments

      - name: Build Static Site
        run: npm run build # Assumes your build script is 'build' in package.json

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/dist' # Path to your built static files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4